esphome:
  name: bathroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.110
    gateway: 192.168.5.1
    subnet: 255.255.255.0
    dns1: 192.168.7.50

logger:

mqtt:
  broker: !secret mqtt_broker

ota:

i2c:
  scan: True
  id: bus_a

switch:
  - platform: restart
    name: "Bathroom Sensor Restart"
binary_sensor:
  - platform: status
    name: "Bathroom Sensor Status"

sensor:
  - platform: wifi_signal
    name: "Bathroom Sensor Signal"
    update_interval: 60s
  - platform: bme280
    id: bme280bathoom
    temperature:
      name: "Bathroom Temperature"
      id: bathroom_temp
      oversampling: 16x  
      filters:
        - median:
            window_size: 5
            send_every: 6
            send_first_at: 1          
    pressure:
      name: "Bathroom Pressure"
      oversampling: 16x  
      filters:
        - median:
            window_size: 15
            send_every: 60
            send_first_at: 1        
    humidity:
      name: "Bathroom Humidity"
      oversampling: 16x      
      filters:
        - median:
            window_size: 5
            send_every: 6
            send_first_at: 1         
    address: 0x77
    update_interval: 5s