esphome:
  name: esp-bed
  platform: ESP32
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.211
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns_server

  ap:
    ssid: "Bed Fallback Hotspot"
    password: "E12bcaWpvNMD"

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

# ######### Switches ##########

switch:
  - platform: restart
    name: "Bed Sensor Restart"

# ######### Sensors ##########
sensor:
  - platform: wifi_signal
    name: "Bed Sensor Signal"
    update_interval: 1min
    force_update: true
    expire_after: 30min
    filters:
      - median:
          window_size: 31
          send_every: 15
          send_first_at: 3
          
  - platform: uptime
    name: "Bed Sensor Uptime"
    expire_after: 30min
    
binary_sensor:
  - platform: status
    name: "Bed Sensor Status"
    
    
# ######### Lights ##########

e131:
  method: multicast

light:
  - platform: partition
    name: "Bed Jamie"
    restore_mode: ALWAYS_OFF
    segments:
      - id: bed_ledstrip
        from: 0
        to: 120
    effects:
      - addressable_rainbow:    
      - addressable_scan:
          name: Fast Scan Effect
          move_interval: 3ms
          scan_width: 3    
      - addressable_lambda:
          name: Bed Night Light
          update_interval: 15ms
          lambda: |-
            static uint16_t current_led = 0;
            if (initial_run) {
              current_led = 0;
              it.all() = Color::BLACK;
              // optionally do a return so nothing happens until the next update_interval
              return;
            }
            
            else if( current_led >= it.size()+1 )
              return;
            
            else if( current_led % 4 == 0 )
              it[current_led] = Color(50,0,0);
            
            current_led++;

        
  - platform: partition
    name: "Bed Footboard"
    restore_mode: ALWAYS_OFF
    segments:
      - id: bed_ledstrip
        from: 121
        to: 208
    effects:
      - addressable_rainbow:    
      - addressable_scan:
          name: Fast Scan Effect
          move_interval: 3ms
          scan_width: 3
      - addressable_lambda:
          name: Bed Night Light
          update_interval: 15ms
          lambda: |-
            static uint16_t current_led = 0;
            if (initial_run) {
              current_led = 0;
              it.all() = Color::BLACK;
              // optionally do a return so nothing happens until the next update_interval
              return;
            }
            
            else if( current_led >= it.size()+1 )
              return;
            
            else if( current_led % 4 == 0 )
              it[current_led] = Color(50,0,0);
            
            current_led++;

  - platform: partition
    name: "Bed Kim"
    restore_mode: ALWAYS_OFF
    segments:
      - id: bed_ledstrip
        from: 209
        to: 338
    effects:
      - addressable_rainbow:
      - addressable_scan:
          name: Fast Scan Effect
          move_interval: 3ms
          scan_width: 3
      - addressable_lambda:
          name: Bed Night Light
          update_interval: 15ms
          lambda: |-
            static uint16_t current_led = 0;
            if (initial_run) {
              current_led = 0;
              it.all() = Color::BLACK;
              // optionally do a return so nothing happens until the next update_interval
              return;
            }
            
            else if( current_led >= it.size()+1 )
              return;
            
            else if( current_led % 4 == 0 )
              it[current_led] = Color(50,0,0);
            
            current_led++;

  - platform: partition
    name: "Bed Headboard"
    restore_mode: ALWAYS_OFF
    segments:
      - id: bed_ledstrip
        from: 339
        to: 427
    effects:
      - addressable_rainbow:    
      - addressable_scan:
          name: Fast Scan Effect
          move_interval: 3ms
          scan_width: 3
      - addressable_lambda:
          name: Bed Night Light
          update_interval: 15ms
          lambda: |-
            static uint16_t current_led = 0;
            if (initial_run) {
              current_led = 0;
              it.all() = Color::BLACK;
              // optionally do a return so nothing happens until the next update_interval
              return;
            }
            
            else if( current_led >= it.size()+1 )
              return;
            
            else if( current_led % 4 == 0 )
              it[current_led] = Color(50,0,0);
            
            current_led++;

  - platform: partition
    name: "Bed Base"
    restore_mode: ALWAYS_OFF
    segments:
      - id: bed_ledstrip
        from: 0
        to: 338
        
  - platform: fastled_spi
    chipset: DOTSTAR
    data_pin: 18
    clock_pin: 5
    num_leds: 428
    rgb_order: BGR
    max_refresh_rate: 1ms
    restore_mode: ALWAYS_OFF
    name: "Bed"
    id: bed_ledstrip
    effects:
      - e131:
          name: "Music Sync"
          universe: 1
          channels: RGB
      - addressable_color_wipe:
      - addressable_rainbow:
      - addressable_scan:
          name: Fast Scan Effect
          move_interval: 3ms
          scan_width: 3
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 15%          
      - addressable_lambda:
          name: Bed Night Light
          update_interval: 20ms
          lambda: |-
            static uint16_t current_led = 0;
            if (initial_run) {
              current_led = 0;
              it.all() = Color::BLACK;
              // optionally do a return so nothing happens until the next update_interval
              return;
            }
            
            else if( current_led >= it.size()+1 )
              return;
            
            else if( current_led % 4 == 0 )
              it[current_led] = Color(50,0,0);
            
            current_led++;

###############################
captive_portal:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker

ota: