sensor:
  - platform: bh1750
    name: "Ambient Light"
    address: 0x23
    update_interval: 60s
    expire_after: 1h 
    filters:
      - exponential_moving_average:
          alpha: 0.2
          send_every: 60
          send_first_at: 1