substitutions:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
  manual_ip:
    static_ip: 192.168.7.239
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.50
  
  domain: .home.thebeginfamily.com

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: 192.168.7.60

mqtt:
  broker: 192.168.7.60

# #######################################

switch:
  - platform: restart
    name: "Restart"
  - platform: shutdown
    name: "Shutdown"

button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic

# #######################################

sensor:     
  - platform: uptime
    name: "Uptime"
    expire_after: 30min

# #######################################

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true