substitutions:
  name: esp-dining-room-env
  friendly_name: "Dining Room Env"
  area: "Dining Room"
  ip_addr: 192.168.4.27
  bme280_temperature_offset: "-2.0"
  board: "nodemcuv2"

esp8266:
  board: ${board}

packages:
  basic: !include common/basic.yaml
  bme680: !include common/bme280.yaml