substitutions:
  name: esp-dining-room-env
  friendly_name: "Dining Room Env"
  area: "Dining Room"
  ip_addr: 192.168.5.112

esphome:
  board: nodemcuv2
  platform: ESP8266

packages:
  basic: !include common/basic.yaml
  bme680: !include common/bme680.yaml      