substitutions:
  name: esp32-energy1
  area: "Playroom"
  friendly_name: "Energy Monitor 1"
  ip_addr: 192.168.4.28
  board: "nodemcu-32s"

esp32:
  board: ${board}
  framework:
    type: arduino

packages:
  basic: !include common/basic.yaml

spi:
  clk_pin: 18 #P18
  miso_pin: 19 #P19
  mosi_pin: 23  #P23

sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: "Energy Line Voltage A"
      current:
        name: "Energy Current A"  
      power:
        name: "Energy Active Power A"
        filters:
          - multiply: -1.0        
      reactive_power:
        name: "Energy Reactive Power A"
        filters:
          - multiply: -1.0
      power_factor:
        name: "Energy Power Factor A"
        filters:
          - multiply: -1.0        
      gain_voltage: 3920
      gain_ct: 39473
    phase_c:
      current:
        name: "Energy Current B"
      power:
        name: "Energy Active Power B"
        filters:
          - multiply: 1.0
      reactive_power:
        name: "Energy Reactive Power B"
        filters:
          - multiply: 1.0        
      power_factor:
        name: "Energy Power Factor B"
        filters:
          - multiply: 1.0        
      gain_voltage: 3920
      gain_ct: 39473
    frequency:
      name: "Energy Line Frequency"
    chip_temperature:
      name: "Energy Chip Temperature"
    line_frequency: 60Hz
    current_phases: 2
    gain_pga: 2X
    update_interval: 60s

###############################