substitutions:
  name: esp32-familyroom-env
  friendly_name: "Family Room Env"
  ip_addr: 192.168.5.110
  board: nodemcu-32s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: ${board}
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: ${ip_addr}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns_server

  ap:
    ssid: "${name}"
    password: "E12bcaWpvNMD"

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

mqtt:
  broker: !secret mqtt_broker
  topic_prefix: esphome/devices/${name}
  birth_message:
    topic: esphome/availability/${name}
    payload: online
  will_message:
    topic: esphome/availability/${name}
    payload: offline  

# #######################################
logger:

api:
  password: ""

ota:
  password: ""
# #######################################

###############################

i2c:
  scan: True
  id: bus_a

# ######### Switches & Buttons  ##########
switch:
  - platform: restart
    name: "Restart"
  - platform: shutdown
    name: "Shutdown"

button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic
    

# ######### Sensors ##########
binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: Uptime
    expire_after: 30min

  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 1min
    force_update: true
    expire_after: 30min
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 300
          send_first_at: 1

  - platform: scd30
    co2:
      name: "CO₂"
      accuracy_decimals: 1
    temperature:
      id: temp
      name: "Temperature"
      accuracy_decimals: 2
    humidity:
      id: humid
      name: "Humidity"
      accuracy_decimals: 1
    #temperature_offset: 1.5 °C
    address: 0x61
    update_interval: 5s

  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 300
            send_first_at: 1    
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 300
            send_first_at: 1
    compensation:
      temperature_source: temp
      humidity_source: humid      
    address: 0x58
    update_interval: 1s

  - platform: sps30
    id: sps30_fam
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "pm_1_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "pm_2_5"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "pm_4_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "pm_10_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pmc_0_5:
      name: "PM <0.5µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_0_5"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pmc_1_0:
      name: "PM <1µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_1_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pmc_2_5:
      name: "PM <2.5µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_2_5"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pmc_4_0:
      name: "PM <4µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_4_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pmc_10_0:
      name: "PM <10µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_10_0"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
      expire_after: 8h
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 30
            send_first_at: 1
    address: 0x69
    update_interval: 10s    