substitutions:
  name: esp32-familyroom-env
  area: "Family Room"
  friendly_name: "Family Room Env"
  ip_addr: 192.168.4.23
  bme680_temperature_offset: "-1.5"
  board: "featheresp32"

esp32:
  board: ${board}
  framework:
    type: arduino

packages:
  basic: !include common/basic.yaml
  feather_battery: !include common/feather_battery.yaml
  sps30: !include common/sps30.yaml
  scd30: !include common/scd30.yaml
  bme680: !include common/bme680.yaml
  bh1750: !include common/bh1750.yaml