esphome:
  name: flextest
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.102
    gateway: 192.168.5.1
    subnet: 255.255.255.0
    dns1: 192.168.7.50

binary_sensor:
  - platform: status
    name: "FlexTest Status"
sensor:
  - platform: wifi_signal
    name: "FlexTest Signal"
    update_interval: 10s
    
logger:

mqtt:
  broker: !secret mqtt_broker

ota:
