substitutions:
  name: esp32-humidifier
  friendly_name: "Humidifier Control"
  area: "Mechanicals"
  ip_addr: 192.168.4.20
  bme680_temperature_offset: "0.0"
  board: "featheresp32"

esp32:
  board: ${board}
  framework:
    type: arduino

esphome:
  includes:
    - dewpoint.h

# Need to set the combined household humidity sensors to the value
# of the family room at boot because it takes a while for the combined sensor
# to settle in and emit values
wifi:
  on_connect:
    - text_sensor.template.publish:
        id: humidifier_status
        state: "off"
    - delay: 15s
    - lambda: !lambda id(indoor_humid).publish_state(id(familyroom_humid).state);
    - lambda: !lambda id(indoor_temp).publish_state(id(familyroom_temp).state);

# ######### Switches & Buttons  ##########
switch:
  - platform: template
    id: fan_mode_on
    internal: true
    optimistic: true
    turn_on_action:
      - logger.log: "Furnace fan is turned on!"
    turn_off_action:
      - logger.log: "Furnace fan is turned off!"
      - switch.turn_off: call_humid

  - platform: template
    id: require_heat
    name: "Require Furnace Heat Mode"
    optimistic: true
    icon: "mdi:heat-wave"
    restore_mode: "ALWAYS_ON"

  - platform: template
    id: avoid_condensation
    name: "Avoid Window Condensation"
    optimistic: true
    icon: "mdi:snowflake-melt"
    restore_mode: "ALWAYS_ON"
    turn_on_action:
      - logger.log: "Avoid Window Condensation ON"
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);"       
    turn_off_action:
      - logger.log: "Avoid Window Condensation OFF"
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);"

  - platform: template
    id: pause_humid
    icon: "mdi:pause-box"
    name: "Pause Humidifer"
    restore_mode: "RESTORE_DEFAULT_OFF"   
    optimistic: false
    turn_on_action:
      - logger.log: "Humidifer paused"
    turn_off_action:
      - logger.log: "Humidifer unpaused"

  - platform: gpio
    id: call_humid
    pin: 26
    name: "Call Humidity"
    internal: true
    on_turn_on:
      - text_sensor.template.publish:
          id: humidifier_status
          state: "on"
      - logger.log: "HUMIDIFIER STEAM ON"      
    on_turn_off:
      - logger.log: "HUMIDIFIER STEAM OFF"

button:
  - platform: template
    id: toggle_steam
    name: "Toggle Steam"
    icon: mdi:waves-arrow-up
    on_press:
      - if:
          condition:
            text_sensor.state:
              id: humidifier_status
              state: 'off'     
          then:
            - if:
                condition:
                  not:
                    - switch.is_on: pause_humid
                then:
                  - text_sensor.template.publish:
                      id: humidifier_status
                      state: "starting"
                  - logger.log: "Setting furnace fan mode to on."              
                  - homeassistant.service:
                      service: climate.set_fan_mode
                      data:
                        entity_id: climate.main_floor
                        fan_mode: "on"
                  - wait_until:
                      condition:
                        switch.is_on: fan_mode_on
                      timeout: 60s
                  - if: 
                      condition:
                        - switch.is_off: fan_mode_on
                      then:
                        - text_sensor.template.publish:
                            id: humidifier_status
                            state: "fan_error"
                        - logger.log: "Furnace fan timed out."
                        - homeassistant.service:            
                            service: notify.persistent_notification
                            data:
                              message: "Furnace fan timed-out while trying to humidify."
                        - switch.turn_off: call_humid
                      else:
                        - logger.log: "Fan on. Waiting 60 secs to spin up."
                        - delay: 60s
                        - switch.turn_on: call_humid
          else:
            - if:
                condition:
                  text_sensor.state:
                    id: humidifier_status
                    state: 'on'     
                then:
                  - text_sensor.template.publish:
                      id: humidifier_status
                      state: "stopping"
                  - switch.turn_off: call_humid
                  - logger.log: "Waiting 10 mins to turn off furnace fan..."
                  - delay: 10min
                  - homeassistant.service:
                      service: climate.set_fan_mode
                      data:
                        entity_id: climate.main_floor
                        fan_mode: "auto"
                  - logger.log: "Furnace fan mode set to auto."
                  - text_sensor.template.publish:
                      id: humidifier_status
                      state: "off"


# ######### Sensors ##########
binary_sensor:
  - platform: template
    id: heat_mode_satisfied
    internal: true

sensor:
  - platform: mqtt_subscribe
    name: "Humidity Hysteresis"
    id: humid_hysteresis
    topic: esphome/devices/${name}/humidity/hysteresis
    state_class: "measurement"
    device_class: "humidity"
    unit_of_measurement: "%"
    qos: 2
    on_value:
      - logger.log: "Humidity hysteresis adjusted."
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);" 
      - script.execute:
          id: eval_humid
          current_humid: !lambda "return float(id(indoor_humid).state);"

  - platform: mqtt_subscribe
    name: "Humidity Setpoint"
    id: humid_setpoint
    device_class: "humidity"
    state_class: "measurement"
    unit_of_measurement: "%"
    topic: esphome/devices/${name}/humidity/setpoint
    qos: 2
    on_value:
      - logger.log: "Humidity setpoint adjusted."      
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);" 
      - script.execute:
          id: eval_humid
          current_humid: !lambda "return float(id(indoor_humid).state);"

  - platform: template
    id: humid_setpoint_adjusted
    name: "Adjusted Humidity Setpoint"
    internal: false
    icon: "mdi:water-percent-alert"
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"

  - platform: mqtt_subscribe
    name: "Window R-Value"
    id: r_value
    topic: esphome/devices/${name}/r_value
    qos: 2
    state_class: "measurement"
    on_value:
      - logger.log: "Window R-Value adjusted."
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(x);"  

  - platform: homeassistant
    id: outdoor_temp
    entity_id: !secret weather_sensor
    attribute: temperature
    on_value:
      - logger.log:
          format: "Outdoor temperature changed to %.1f."
          args: [ 'id(outdoor_temp).state' ]     
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(x);"
          r_val: !lambda "return float(id(r_value).state);"          

  - platform: homeassistant
    id: familyroom_temp
    entity_id: sensor.esp32_familyroom_env_temperature
  - platform: homeassistant
    id: familyroom_humid
    entity_id: sensor.esp32_familyroom_env_humidity

  - platform: homeassistant
    id: diningroom_temp
    entity_id: sensor.esp_dining_room_env_temperature
  - platform: homeassistant
    id: diningroom_humid
    entity_id: sensor.esp_dining_room_env_humidity

#####################################################
  # combine temperature readings throughout the house
  - platform: kalman_combinator
    name: "Household Temperature"
    id: indoor_temp
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°F"
    process_std_dev: 0.060
    sources:
      - source: familyroom_temp
        error: 1.0
      - source: diningroom_temp
        error: 1.0
    on_value:
      - logger.log:
          format: "Indoor temperature changed to %.1f."
          args: [ 'id(indoor_temp).state' ]
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(x);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);"


  # combine humidity readings throughout the house
  - platform: kalman_combinator
    name: "Household Humidity"
    id: indoor_humid
    device_class: "humidity"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    process_std_dev: 0.060
    sources:
      - source: familyroom_humid
        error: 1.0
      - source: diningroom_humid
        error: 1.0
      #- source: temperature_sensor_2
      #  error: !lambda |-
      #    return 0.5 + std::abs(x - 25) * 0.023
    on_value:
      - logger.log: "Household humidity changed"
      - logger.log:
          format: "Household humidity changed to %.1f."
          args: [ 'id(indoor_humid).state' ] 
      - script.execute:
          id: update_max_throttled_humid
          indoor_temp: !lambda "return float(id(indoor_temp).state);"
          outdoor_temp: !lambda "return float(id(outdoor_temp).state);"
          r_val: !lambda "return float(id(r_value).state);" 
      - script.execute:
          id: eval_humid
          current_humid: !lambda "return float(x);"
    filters:
      - filter_out: nan
      - round: 0
      - lambda: !lambda "return int(x);"

text_sensor:
  - platform: template
    name: "Humidifer Status"
    id: humidifier_status
    icon: "mdi:air-humidifier"

  - platform: homeassistant
    id: fan_mode
    entity_id: climate.main_floor
    attribute: fan_mode
    on_value:
      then:
        - lambda: |-
            if (x == "on") {
              id(fan_mode_on).publish_state(true);
            } else {
              id(fan_mode_on).publish_state(false);
            }

  - platform: homeassistant
    id: heat_mode
    entity_id: climate.main_floor
    on_value:
      then:
        - lambda: |-
            if ( (x == "heat" || x == "heat_cool") || (id(require_heat).state == false) ){
              id(heat_mode_satisfied).publish_state(true);
            } else {
              id(heat_mode_satisfied).publish_state(false);
            }

script:
  - id: eval_humid
    parameters:
      current_humid: float
    then:
      - if:
          condition:
            and:
              - binary_sensor.is_on: heat_mode_satisfied
              - lambda: |-
                  if( int(current_humid) <= id(humid_setpoint_adjusted).state - (id(humid_hysteresis).state / 2) ) {
                    return true;
                  } else {
                    return false;
                  }
              - text_sensor.state:
                  id: humidifier_status
                  state: 'off'
          then:
              - logger.log: "Need to turn ON the steam!"
              - button.press: toggle_steam 
      - if:
          condition:
            and:
              - lambda: |-
                  if( int(current_humid) >= id(humid_setpoint_adjusted).state + (id(humid_hysteresis).state / 2) ) {
                    return true;
                  } else {
                    return false;
                  }
              - text_sensor.state:
                  id: humidifier_status
                  state: 'on'
          then:
            - logger.log: "Need to turn OFF the steam!" 
            - button.press: toggle_steam

  - id: update_max_throttled_humid
    parameters:
      indoor_temp: float
      outdoor_temp: float
      r_val: float
    then:
      - lambda: |-
            double indoor_temp_c = float(5.0/9.0 * (indoor_temp - 32.0)); // F to C conversion
            double outdoor_temp_c = float(5.0/9.0 * (outdoor_temp - 32.0)); // F to C conversion

            ESP_LOGD("lambda", "indoor_temp_c set to: %f", indoor_temp_c);
            ESP_LOGD("lambda", "outdoor_temp_c set to: %f", outdoor_temp_c);
            ESP_LOGD("lambda", "r_val set to: %f", r_val);

            if( isnan(indoor_temp_c) || isnan(outdoor_temp_c) ) {
                id(humid_setpoint_adjusted).publish_state(0.0);
                ESP_LOGE("lambda", "indoor_temp_c and/or outdoor_temp_c is NaN. Throttled to 0.");
            } else if( id(avoid_condensation).state == true) {      

              int humid_limit;

              // Calculate the window surface temperature using the R-value
              double T_window_surface_with_R = indoor_temp_c - (indoor_temp_c - outdoor_temp_c) / r_val;
              ESP_LOGD("lambda", "T_window_surface_with_R set to: %f", T_window_surface_with_R);

              // Calculate the RH at which condensation occurs
              double rh_at_condensation_with_R = calc_relative_humidity(indoor_temp_c, T_window_surface_with_R);
              ESP_LOGD("lambda", "rh_at_condensation_with_R set to: %f", rh_at_condensation_with_R); 

              // Got the dewpoint, now we need a buffer so we don't exceed it
              int h_buffer = int(round(id(humid_hysteresis).state / 2));

              humid_limit = int(rh_at_condensation_with_R) - h_buffer;
              if( humid_limit <= int(id(humid_setpoint).state) ) {
                id(humid_setpoint_adjusted).publish_state(humid_limit);
                ESP_LOGD("lambda", "THROTTLED humid_max_throttled set to: %d", humid_limit);
              } else {
                id(humid_setpoint_adjusted).publish_state(int(id(humid_setpoint).state));
              }
            } else {
              ESP_LOGD("lambda", "avoid_condensation is apparently false");
              ESP_LOGD("lambda", "UNTHROTTLED humid_max_throttled");
              id(humid_setpoint_adjusted).publish_state(int(id(humid_setpoint).state));
            }

packages:
  basic: !include common/basic.yaml
  bme680: !include common/bme680.yaml