# KeeYees ESP32S ESP32 Development Board 2.4 GHz Dual Core
# WLAN WiFi + Bluetooth 2-in-1 Microcontroller ESP-WROOM-32 
# Chip for Arduino (38PIN Narrow Version, 2PCS) 
# https://www.amazon.com/gp/product/B07QCP2451
# ***** Crappy board, don't buy more. ******

substitutions:
  name: esp32-kitchen-sink
  friendly_name: "Kitchen Sink"
  area: "Kitchen"
  ip_addr: 192.168.4.33
  board: "nodemcu-32s"
  bme680_temperature_offset: "-0.7"
  
esp32:
  board: ${board}
  framework:
    type: esp-idf

packages:
  basic: !include common/basic.yaml
  bme680: !include common/bme680.yaml

output:
  - platform: ledc
    pin: GPIO26
    id: cold_white_out
    frequency: "4882Hz"
    inverted: false

  - platform: ledc
    pin: GPIO27
    id: warm_white_out
    frequency: "4882Hz"
    inverted: false

light:
  - platform: cwww
    name: "Sink Light"
    cold_white: cold_white_out
    warm_white: warm_white_out
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: false
    gamma_correct: 1.35   # lower if doesn't dim far enough
    restore_mode: ALWAYS_OFF    