esphome:
  name: esp-ro1
  platform: ESP32
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.179
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns_server

  ap:
    ssid: "RO1 Fallback Hotspot"
    password: "E12bcaWpvNMD"

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

# ######### Switches ##########

switch:
  - platform: restart
    name: "RO1 Sensor Restart"

i2c:
  scan: True
  sda: 23
  scl: 22
  
# ######### Sensors ##########

binary_sensor:
  - platform: status
    name: "RO1 Sensor Status"

ads1115:
  - address: 0x48
  
sensor:
  - platform: wifi_signal
    name: "RO1 Sensor Signal"
    update_interval: 1min
    force_update: true
    expire_after: 30min
    filters:
      - median:
          window_size: 31
          send_every: 15
          send_first_at: 1

  - platform: uptime
    name: "RO1 Sensor Uptime"
    expire_after: 30min    
    
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048
    name: "To RO1"
    update_interval: 60s
    unit_of_measurement: "ppm"
    icon: "mdi:pipe"
    accuracy_decimals: 0
    force_update: true
    expire_after: 24h
    filters:
      - calibrate_linear:
        - 0.0163 -> 0.0
        - 0.0913 -> 25.0
        - 0.1345 -> 50.0
        - 0.2593 -> 100.0
        - 0.5205 -> 250.0
        - 0.9985 -> 500.0
        - 1.3880 -> 750.0
        - 1.7487 -> 1000.0
      - median:
          window_size: 481
          send_every: 240
          send_first_at: 1
 
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 2.048
    name: "From RO1"
    update_interval: 60s
    unit_of_measurement: "ppm"
    icon: "mdi:cup-water"
    accuracy_decimals: 0
    force_update: true
    expire_after: 24h
    filters:
      - calibrate_linear:
        - 0.016 -> 0.0
        - 0.0881 -> 25.0
        - 0.1257 -> 50.0
        - 0.2350 -> 100.0
        - 0.465 -> 250.0
        - 0.874 -> 500.0
        - 1.316 -> 750.0
        - 1.566 -> 1000.0
      - median:
          window_size: 481
          send_every: 240
          send_first_at: 1

  - platform: ads1115
    id: pressure_input
    multiplexer: 'A2_GND'
    gain: 2.048
    name: "Pressure Input"
    update_interval: 60s
    unit_of_measurement: "psi"
    icon: "mdi:gauge"
    accuracy_decimals: 0
    force_update: true
    expire_after: 24h
    filters:
      - calibrate_linear:
        - 0.5 -> 0.0
        - 1.5 -> 25.0
        - 2.5 -> 50.0
        - 3.5 -> 75.0
        - 4.5 -> 100.0
      - median:
          window_size: 481
          send_every: 240
          send_first_at: 1

  - platform: ads1115
    id: pressure_out
    internal: true
    multiplexer: 'A3_GND'
    gain: 2.048
    name: "Pressure Out"
    update_interval: 200ms
    unit_of_measurement: "psi"
    icon: "mdi:gauge"
    accuracy_decimals: 0
    force_update: true
    expire_after: 24h
    filters:
      - calibrate_linear:
        - 0.5 -> 0.0
        - 1.5 -> 25.0
        - 2.5 -> 50.0
        - 3.5 -> 75.0
        - 4.5 -> 100.0
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1          
          
    - platform: template
      name: "Pressure Service"
      unit_of_measurement: "psi"
      icon: "mdi:gauge"
      update_interval: 60s      
      accuracy_decimals: 0
      force_update: true
      expire_after: 24h
      lambda: |-
        if (id(pressure_out).state) {
          return 42.0;
        } else {
          return 0.0;
        }      
      filters:
        - median:
            window_size: 481
            send_every: 240
            send_first_at: 1         

###############################
captive_portal:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker

ota:    