substitutions:
  name: esp32-scuba-room
  friendly_name: "Scuba Room"
  area: "Shop"
  ip_addr: 192.168.4.32
  board: "nodemcu-32s"
  aht20_temperature_offset: "0"

esp32:
  board: ${board}
  framework:
    type: arduino

sensor:
  - platform: absolute_humidity
    name: Absolute Humidity
    temperature: aht20_temperature
    humidity: aht20_humidity

packages:
  basic: !include common/basic.yaml
  aht20: !include common/aht20.yaml