substitutions:
  name: esp32-shop-thermostat
  area: "Shop"
  friendly_name: "Shop Thermostat"
  ip_addr: 192.168.5.115
  bme680_temperature_offset: "-1.5"

esp32:
  board: featheresp32
  framework:
    type: arduino

i2c:
  scan: True
  id: bus_a

switch:
  - platform: gpio
    id: call_heat
    pin: 21
    name: "Call Heat"

apds9960:
  address: 0x39
  update_interval: 60s

sensor:
  - platform: apds9960
    type: CLEAR
    name: "APDS9960 Clear Channel"

  # - platform: adc
  #   pin: A1 # Pin 25, ADC #2
  #   name: "LNG Levels"
  #   update_interval: 60s

#   - platform: adc
#     pin: A2 # Pin 34, ADC #1
#     name: "CO Levels"
#     update_interval: 60s

binary_sensor:
  - platform: apds9960
    direction: UP
    name: "APDS960 Up Movement"
    internal: true
    on_state:
      - switch.toggle: call_heat
  
  - platform: apds9960
    direction: DOWN
    name: "APDS960 Down Movement"
    internal: true
    on_state:
      - switch.toggle: call_heat

  - platform: apds9960
    direction: LEFT
    name: "APDS960 Down Movement"
    internal: true
    on_state:
      - logger.log: "LEFT!"

  - platform: apds9960
    direction: RIGHT
    name: "APDS960 Down Movement"
    internal: true
    on_state:
      - logger.log: "RIGHT!"


  # - platform: gpio
  #   pin: 26
  #   name: "Garage PIR Sensor"
  #   device_class: motion
  #   internal: true
  #   id: pir
  #   on_state:
  #     then:
  #       if:
  #         condition:
  #           and:
  #             - binary_sensor.is_on: pir
  #         then:
  #             - binary_sensor.template.publish:
  #                 id: thermo_motion
  #                 state: ON
  #         else:
  #             - binary_sensor.template.publish:
  #                 id: thermo_motion
  #                 state: OFF

  # - platform: template
  #   name: "Thermostat Motion"
  #   id: thermo_motion
  #   device_class: motion

# font:
#   - file: 'arial.ttf'
#     id: font1
#     size: 10

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     reset_pin: A5
#     address: 0x3C
#     lambda: |-
#       it.print(0, 0, id(font1), "Hello World!");

packages:
  basic: !include common/basic.yaml
  #feather_battery: !include common/feather_battery.yaml
  bme680: !include common/bme680.yaml
