substitutions:
  name: esp32-test
  area: "test"
  friendly_name: "test"
  ip_addr: 192.168.4.122
  board: "featheresp32"

esp32:
  board: ${board}
  framework:
    type: arduino
# logger:
#   hardware_uart: USB_SERIAL_JTAG
#   level: DEBUG

packages:
  basic: !include common/basic.yaml

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

climate:
  - platform: mitsubishi_heatpump
    name: "Office Minisplit"
    hardware_uart: UART0
    update_interval: 500ms