substitutions:
  name: esp32-water
  friendly_name: "Water Systems"
  area: "Laundry"
  ip_addr: 192.168.5.239

esp32:
  board: featheresp32
  framework:
    type: arduino

sensor:
  - platform: ultrasonic
    trigger_pin: 13
    echo_pin: 27
    name: "Brine Tank Level (Primary)"
    # 40" tall
    id: brine_tank_primary
    unit_of_measurement : "%"
    state_class: "measurement"
    icon: "mdi:cup-water"
    update_interval: 1min
    expire_after: 24h
    accuracy_decimals: 0
    force_update: true
    filters:
      - lambda: "return (( 43 - (x * 39.3701) )/40)*100;"
      - filter_out: nan
      - exponential_moving_average:
          alpha: 0.2
          send_every: 480
          send_first_at: 1

  - platform: ultrasonic
    trigger_pin: 14
    echo_pin: 15
    name: "Brine Tank Level (Secondary)"
    # 33" tall
    id: brine_tank_secondary
    unit_of_measurement : "%"
    state_class: "measurement"
    icon: "mdi:cup-water"
    update_interval: 1min
    expire_after: 24h
    accuracy_decimals: 0
    force_update: true
    filters:
      - lambda: "return (( 36 - (x * 39.3701) )/33)*100;"
      - filter_out: nan
      - exponential_moving_average:
          alpha: 0.2
          send_every: 480
          send_first_at: 1
          
  - platform: mqtt_subscribe
    name: "Injection Pump"
    id: injection_pump_mqtt
    topic: irrigation/injection_pump

switch:
  - platform: gpio
    pin: A0
    name: "Injection Pump Relay"
    id: injection_pump_relay
    inverted: no
    restore_mode: ALWAYS_OFF

packages:
  basic: !include common/basic.yaml