esphome:
  name: watersoftener
  platform: ESP32
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.134
    gateway: 192.168.5.1
    subnet: 255.255.255.0
    dns1: 192.168.7.50

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker

ota:

switch:
  - platform: restart
    name: "Water Softener Sensor Restart"
binary_sensor:
  - platform: status
    name: "Water Softener Status"
sensor:
  - platform: wifi_signal
    name: "Water Softener Signal"
    update_interval: 5min

  - platform: ultrasonic
    trigger_pin: A1
    echo_pin: A0
    name: "Brine Tank 1"
    icon: "mdi:barrel"
    update_interval: 30s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    filters:
      - lambda: return (1.0668-x)*(100/1.0668);
      - median:
          window_size: 25
          send_every: 30
          send_first_at: 5