esphome:
  name: watersoftener
  platform: ESP32
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.134
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns_server
    
time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

logger:

mqtt:
  broker: !secret mqtt_broker

ota:

switch:
  - platform: restart
    name: "Water Softener Sensor Restart"
binary_sensor:
  - platform: status
    name: "Water Softener Status"
sensor:
  - platform: wifi_signal
    name: "Water Softener Sensor Signal"
    update_interval: 5min
    expire_after: 1h
  - platform: uptime
    name: Water Softener Sensor Uptime  
  - platform: ultrasonic
    trigger_pin: A1
    echo_pin: A0
    name: "Brine Tank 1"
    icon: "mdi:barrel"
    update_interval: 30s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    expire_after: 24h
    filters:
      - lambda: return (1.0668-x)*(100/1.0668);
      - delta: 3
      - median:
          window_size: 25
          send_every: 30
          send_first_at: 5