substitutions:
  name: esp32-water
  friendly_name: "Water Systems"
  area: "Laundry"
  ip_addr: 192.168.4.21
  board: "featheresp32"

esp32:
  board: ${board}
  framework:
    type: arduino

packages:
  basic: !include common/basic.yaml
    
sensor:
  - platform: ultrasonic
    trigger_pin: 13
    echo_pin: 27
    name: "Brine Tank Level (Primary)"
    id: brine_tank_primary
    unit_of_measurement: "%"
    state_class: measurement
    icon: "mdi:cup-water"
    update_interval: 60s
    expire_after: 24h
    accuracy_decimals: 0
    timeout: 1.2m            # speed up timeouts; tank < 1.2 m. Defaults to 2 m. 
    filters:
      # A) operate on *distance* (x is in meters)
      - median:
          window_size: 7       # ~7 minutes of readings
          send_every: 1
          send_first_at: 1

      # B) map distance -> % with correct linear mapping + outlier rejection
      - lambda: |-
          // Geometry in centimeters
          const float TANK_HEIGHT_CM = 102.0;
          const float MIN_WATER_LEVEL_CM = 12.0;
          const float GAP_FULL_CM = 10.0;
          const float TOL_CM = 2.0;

          if (isnan(x)) return NAN;

          const float d_cm = x * 100.0f;                 // raw distance (cm)
          const float d_empty = TANK_HEIGHT_CM - MIN_WATER_LEVEL_CM;
          const float d_full  = GAP_FULL_CM;

          // reject clearly bogus echoes outside expected range (± tolerance)
          if (d_cm < (d_full - TOL_CM) || d_cm > (d_empty + TOL_CM)) return NAN;

          float pct = 100.0f * (d_empty - d_cm) / (d_empty - d_full);
          if (pct < 0.0f)   pct = 0.0f;
          if (pct > 100.0f) pct = 100.0f;
          return pct;

      # C) drop invalids produced by the lambda
      - filter_out: nan

      # D) light exponential smoothing on % to soften the remaining jitter
      - exponential_moving_average:
          alpha: 0.2          # higher = more responsive; 0.1–0.2 is a good start

      # E) update only on real changes, but still send a heartbeat
      - delta: 0.5            # publish immediately if change ≥ 0.5 %
      - heartbeat: 10min      # otherwise, re‑publish the current value every 10 min


  - platform: ultrasonic
    trigger_pin: 14
    echo_pin: 15
    name: "Brine Tank Level (Secondary)"
    id: brine_tank_secondary
    unit_of_measurement: "%"
    state_class: measurement
    icon: "mdi:cup-water"
    update_interval: 61s
    expire_after: 24h
    accuracy_decimals: 0
    timeout: 1.2m
    filters:
      # A) operate on *distance* (x is in meters)
      - median:
          window_size: 7       # ~7 minutes of readings
          send_every: 1
          send_first_at: 1

      # B) map distance -> % with correct linear mapping + outlier rejection
      - lambda: |-
          // Geometry in centimeters
          const float TANK_HEIGHT_CM = 84.0;   // 102.0 for primary tank
          const float MIN_WATER_LEVEL_CM = 12.0;
          const float GAP_FULL_CM = 10.0;
          const float TOL_CM = 2.0;

          if (isnan(x)) return NAN;

          const float d_cm = x * 100.0f;                 // raw distance (cm)
          const float d_empty = TANK_HEIGHT_CM - MIN_WATER_LEVEL_CM;
          const float d_full  = GAP_FULL_CM;

          // reject clearly bogus echoes outside expected range (± tolerance)
          if (d_cm < (d_full - TOL_CM) || d_cm > (d_empty + TOL_CM)) return NAN;

          float pct = 100.0f * (d_empty - d_cm) / (d_empty - d_full);
          if (pct < 0.0f)   pct = 0.0f;
          if (pct > 100.0f) pct = 100.0f;
          return pct;

      # C) drop invalids produced by the lambda
      - filter_out: nan

      # D) light exponential smoothing on % to soften the remaining jitter
      - exponential_moving_average:
          alpha: 0.2          # higher = more responsive; 0.1–0.2 is a good start

      # E) update only on real changes, but still send a heartbeat
      - delta: 0.5            # publish immediately if change ≥ 0.5 %
      - heartbeat: 10min      # otherwise, re‑publish the current value every 10 min

          
  - platform: mqtt_subscribe
    name: "Injection Pump"
    id: injection_pump_mqtt
    topic: irrigation/injection_pump

switch:
  - platform: gpio
    pin: A0
    name: "Injection Pump Relay"
    id: injection_pump_relay
    inverted: no
    restore_mode: ALWAYS_OFF