esphome:
  name: esp-water
  platform: ESP32
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: False
  reboot_timeout: 15min
  domain: !secret domain
  manual_ip:
    static_ip: 192.168.5.239
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns_server
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Systems Fallback Hotspot"
    password: "E12bcaWpvNMD"

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Detroit"
    servers: !secret ntp_server

# ######### Sensors ##########

sensor:
  - platform: wifi_signal
    name: "Water Systems Signal"
    update_interval: 1min
    force_update: true
    expire_after: 30min
    filters:
      - median:
          window_size: 31
          send_every: 15
          send_first_at: 3
          
  - platform: uptime
    name: "Water Systems Uptime"
    expire_after: 30min
    
  - platform: ultrasonic
    trigger_pin: 13
    echo_pin: 27
    name: "Brine Tank Level (Primary)"
    # 40" tall
    id: brine_tank_primary
    unit_of_measurement : "%"
    icon: "mdi:cup-water"
    update_interval: 1min
    expire_after: 24h
    accuracy_decimals: 0
    force_update: true
    filters:
      - lambda: return (( 43 - (x * 39.3701) )/40)*100;
      - filter_out: nan
      - median:
          window_size: 121
          send_every: 60
          send_first_at: 1

  - platform: ultrasonic
    trigger_pin: 14
    echo_pin: 15
    name: "Brine Tank Level (Secondary)"
    # 33" tall
    id: brine_tank_secondary
    unit_of_measurement : "%"
    icon: "mdi:cup-water"
    update_interval: 1min
    expire_after: 24h
    accuracy_decimals: 0
    force_update: true
    filters:
      - lambda: return (( 36 - (x * 39.3701) )/33)*100;
      - filter_out: nan
      - median:
          window_size: 121
          send_every: 60
          send_first_at: 1
          
  - platform: mqtt_subscribe
    name: "Injection Pump"
    id: injection_pump_mqtt
    topic: irrigation/injection_pump

binary_sensor:
  - platform: status
    name: "Water Systems Status"


# ######### Switches ##########

switch:
  - platform: restart
    name: "Water Systems Restart"
    
  - platform: gpio
    pin: A0
    name: "Injection Pump Relay"
    id: injection_pump_relay
    inverted: no
    restore_mode: ALWAYS_OFF
    
    
    
###############################
captive_portal:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker

ota:
    