sensor:
  # 3.7V lithium cell discharge curve
  - platform: adc
    pin: A13
    name: "Battery Level"
    #icon: "mdi:battery"
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "battery"
    expire_after: 60s
    attenuation: auto
    update_interval: 1s
    filters:
      - multiply: 2.07 # convert measured V to actual battery V
      - calibrate_polynomial:
         degree: 3
         datapoints:        
          - 4.2820 -> 98.9204
          - 4.0564 -> 96.6262
          - 3.9041 -> 92.0378
          - 3.8026 -> 83.9406
          - 3.7519 -> 74.4939
          - 3.7293 -> 66.9366
          - 3.7180 -> 54.2510
          - 3.7179 -> 35.0877
          - 3.7177 -> 14.8448
          - 3.7174 -> 5.9379
          - 3.6955 -> -3.5088
      - clamp:
          max_value: 100
      - exponential_moving_average:
          alpha: 0.5
          send_every: 10
          send_first_at: 1
      - delta: 5.0
    accuracy_decimals: 0