i2c:
  scan: True
  id: bus_a
  
sensor:
  - platform: scd30
    co2:
      name: "CO₂"
      id: co2
      accuracy_decimals: 1
      force_update: true
      expire_after: 60min
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1   
    temperature:
      id: scd30_temp
      name: "SCD30 Temperature"
      accuracy_decimals: 0
      force_update: true
      expire_after: 60min
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    humidity:
      id: scd30_humid
      name: "SCD30 Humidity"
      accuracy_decimals: 0
      force_update: true
      expire_after: 60min
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    address: 0x61
    update_interval: 1s

text_sensor:
  - platform: template
    name: "CO₂ Exposure Classification"
    icon: "mdi:molecule-co2"
    lambda: |-
      if (int(id(co2).state) <= 400) {
        return {"Excellent"};
      }
      else if (int(id(co2).state) <= 1000) {
        return {"Good"};
      }
      else if (int(id(co2).state) <= 1500) {
        return {"Borderline"};
      }
      else if (int(id(co2).state) <= 2000) {
        return {"Poor"};
      }
      else if (int(id(co2).state) <= 5000) {
        return {"Very Poor"};
      }
      else if (int(id(co2).state) > 5000) {
        return {"OSHA Limits Exceeded!"};
      }
      else {
        return {"unknown"};
      }