i2c:
  scan: True
  id: bus_a
  
sensor:
  - platform: sps30
    id: sps30_pm
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "pm_1_0"
      unit_of_measurement: "µg/m³"
      state_class: "measurement"
      expire_after: 8h
      force_update: true
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "pm_2_5"
      unit_of_measurement: "µg/m³"
      state_class: "measurement"      
      expire_after: 8h
      force_update: true
      on_raw_value:
        then:
          - lambda: !lambda "id(pm2_5_24hr).publish_state(x);"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "pm_4_0"
      unit_of_measurement: "µg/m³"
      state_class: "measurement"      
      expire_after: 8h
      force_update: true
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "pm_10_0"
      unit_of_measurement: "µg/m³"
      state_class: "measurement"      
      expire_after: 8h
      force_update: true
      on_raw_value:
        then:
          - lambda: !lambda "id(pm10_24hr).publish_state(x);"      
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pmc_0_5:
      name: "PM <0.5µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_0_5"
      expire_after: 8h
      force_update: true
      state_class: "measurement"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pmc_1_0:
      name: "PM <1µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_1_0"
      expire_after: 8h
      force_update: true
      state_class: "measurement"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pmc_2_5:
      name: "PM <2.5µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_2_5"
      expire_after: 8h
      force_update: true
      state_class: "measurement"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pmc_4_0:
      name: "PM <4µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_4_0"
      expire_after: 8h
      force_update: true
      state_class: "measurement"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pmc_10_0:
      name: "PM <10µm Number concentration"
      unit_of_measurement: "qty/cm³"
      id: "pmc_10_0"
      expire_after: 8h
      force_update: true
      state_class: "measurement"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
      expire_after: 8h
      force_update: true
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 60
            send_first_at: 1
    address: 0x69
    update_interval: 10s

  - platform: template
    name: "PM2_5 24 Hr Moving Average"
    id: pm2_5_24hr
    icon: "mdi:hours-24"
    unit_of_measurement: "µg/m³"
    state_class: "measurement"
    device_class: "pm25"
    expire_after: 5d 
    filters:
      - exponential_moving_average:
          alpha: 0.2
          send_every: 8640 # Once a day at 10s intervals
          send_first_at: 30
    update_interval: 10s

  - platform: template
    name: "PM10 24 Hr Moving Average"
    id: pm10_24hr
    icon: "mdi:hours-24"
    unit_of_measurement: "µg/m³"
    state_class: "measurement"
    device_class: "pm10"
    expire_after: 5d 
    filters:
      - exponential_moving_average:
          alpha: 0.2
          send_every: 8640 # Once a day at 10s intervals
          send_first_at: 30
    update_interval: 10s

text_sensor:
  - platform: template
    name: "PM25 Limits"
    icon: "mdi:weather-dust"
    lambda: |-
      if (int(id(pm2_5_24hr).state) <= 12) {
        return {"Safe"};
      }
      else if (int(id(pm2_5_24hr).state) <= 35.4) {
        return {"Marginally Unsafe"};
      }
      else if (int(id(pm2_5_24hr).state) <= 55.4) {
        return {"Moderately Unsafe"};
      }
      else if (int(id(pm2_5_24hr).state) <= 150.4) {
        return {"Hazardous"};
      }
      else if (int(id(pm2_5_24hr).state) <= 250.4) {
        return {"Very Hazardous"};
      }
      else if (int(id(pm2_5_24hr).state) <= 500) {
        return {"Extremely Hazardous"};
      }
      else if (int(id(pm2_5_24hr).state) > 500) {
        return {"Toxic!"};
      }
      else {
        return {"unknown"};
      }

  - platform: template
    name: "PM10 Limits"
    icon: "mdi:weather-dust"
    lambda: |-
      if (int(id(pm10_24hr).state) <= 54) {
        return {"Safe"};
      }
      else if (int(id(pm10_24hr).state) <= 154) {
        return {"Marginally Unsafe"};
      }
      else if (int(id(pm10_24hr).state) <= 254) {
        return {"Moderately Unsafe"};
      }
      else if (int(id(pm10_24hr).state) <= 354) {
        return {"Hazardous"};
      }
      else if (int(id(pm10_24hr).state) <= 424) {
        return {"Very Hazardous"};
      }
      else if (int(id(pm10_24hr).state) <= 604) {
        return {"Extremely Hazardous"};
      }
      else if (int(id(pm10_24hr).state) > 604) {
        return {"Toxic!"};
      }
      else {
        return {"unknown"};
      }